Chat application layouts implemented
off-art/middle.messenger.praktikum.yandex pull request #1
Opened 2022-09-23 06:27 UTC by off-art

2022-09-23 07:37 UTC, podlovchenko requested changes
Привет, в целом все хорошо, не хватает ссылок на нетлифай и макеты

Также было бы здорово добавить страницу с ссылками на все страницы для 1 и 2 спринтов)

2022-09-23 07:37 UTC, podlovchenko commented on .parcelrc
> +}
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-09-23 07:37 UTC, podlovchenko commented on package.json
> +    "express": "^4.18.1",
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2022-09-23 07:37 UTC, podlovchenko commented on package.json
> +    "@parcel/transformer-less": "^2.6.2",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-09-23 07:37 UTC, podlovchenko commented on package.json
> +    "start": "parcel build src/index.html && node server.js"
Можно так
```suggestion
    "start": "npm run build && node server.js"
```

2022-09-23 07:37 UTC, podlovchenko commented on README.md
> +Добавлю позже...
По заданию нужно добавить ссылку на нетлифай и макеты для сдачи 1 спринта

2022-09-23 07:37 UTC, podlovchenko commented on src/components/ChatItem/ChatItem.less
> +  border-bottom: 1px solid #eaeaea;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту

2022-09-23 07:37 UTC, podlovchenko commented on src/components/ChatItem/ChatItem.less
> +      div {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-09-23 07:37 UTC, podlovchenko commented on package.json
> +    "@parcel/transformer-less": "^2.6.2",
package-lock.json лучше добавить в репозиторий, так будет гарантироваться, что будут установлены те же версии пакетов например на нетлифае

2022-09-23 07:37 UTC, podlovchenko commented on server.js
> +  app.get(link, (req, res) => {
Здесь можно
```suggestion
  app.get('/*', (req, res) => {
```
Чтобы отобразить страницу 404 при неправильном урле

2022-09-23 15:02 UTC, off-art commented on src/components/ChatItem/ChatItem.less
> +  border-bottom: 1px solid #eaeaea;
Справедливо

2022-09-24 09:33 UTC, off-art commented on .parcelrc
> +}
Хотел исправить с добавлением линтера во втором спринте

2022-09-24 10:58 UTC, merged